### PR TITLE
created js file, added working fetch api call for access token

### PR DESCRIPTION
**Pull request by yoojeenkim**

### CODE REVIEW

**Comment by yoojeenkim** [comment]
I ended up not using ajax because I was getting frustrated with it retrieving the access token and passing through CORS security. I just used the fetch() to retrieve the access token and console.log() to test if data is able to pass through the parameters in the URL.

**Review by TammyGagliano — APPROVED** [review]
Looks good, Daniel!

**Review by TammyGagliano — APPROVED** [review]
Everything looks okay to me.

**Review by ldw5 — APPROVED** [review]
Looks good!

**Pull request merged**
